<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<LangVersion>latest</LangVersion>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>Ob.PostgreSql</RootNamespace>
	<AssemblyName>Ob.PostgreSql</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Npgsql" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Ob.Common\Ob.Common.csproj" />
  </ItemGroup>

</Project>
