<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<LangVersion>latest</LangVersion>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>Ob.SqlServer</RootNamespace>
	<AssemblyName>Ob.SqlServer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Ob.Common\Ob.Common.csproj" />
  </ItemGroup>

</Project>
